//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.31 at 12:51:52 AM CEST 
//


package com.ftn.papers_please.model.scientific_paper;

import java.util.Date;
import javax.xml.bind.annotation.adapters.XmlAdapter;

import com.ftn.papers_please.util.DateConverter;

public class Adapter2
    extends XmlAdapter<String, Date>
{


    public Date unmarshal(String value) {
        return (DateConverter.parseYear(value));
    }

    public String marshal(Date value) {
        return (DateConverter.printYear(value));
    }

}
