//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.31 at 12:51:52 AM CEST 
//


package com.ftn.papers_please.model.scientific_paper;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlMixed;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TEmphasis complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TEmphasis"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice maxOccurs="unbounded"&gt;
 *         &lt;element name="b" type="{https://github.com/ivanmihajlov/papers_please}TEmphasis" minOccurs="0"/&gt;
 *         &lt;element name="i" type="{https://github.com/ivanmihajlov/papers_please}TEmphasis" minOccurs="0"/&gt;
 *         &lt;element name="u" type="{https://github.com/ivanmihajlov/papers_please}TEmphasis" minOccurs="0"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TEmphasis", propOrder = {
    "content"
})
public class TEmphasis {

    @XmlElementRefs({
        @XmlElementRef(name = "b", namespace = "https://github.com/ivanmihajlov/papers_please", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "i", namespace = "https://github.com/ivanmihajlov/papers_please", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "u", namespace = "https://github.com/ivanmihajlov/papers_please", type = JAXBElement.class, required = false)
    })
    @XmlMixed
    protected List<Serializable> content;

    /**
     * Gets the value of the content property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the content property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link TEmphasis }{@code >}
     * {@link JAXBElement }{@code <}{@link TEmphasis }{@code >}
     * {@link JAXBElement }{@code <}{@link TEmphasis }{@code >}
     * {@link String }
     * 
     * 
     */
    public List<Serializable> getContent() {
        if (content == null) {
            content = new ArrayList<Serializable>();
        }
        return this.content;
    }

}
