PREFIX xml: <https://github.com/ivanmihajlov/papers_please/> 
PREFIX pred: <https://github.com/ivanmihajlov/papers_please/predicate/> 
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT DISTINCT ?paper
FROM <http://localhost:3030/Papers/data/scientificPapers>
WHERE {
 ?paper pred:quotes ?quotedPaper .
 FILTER( str(?quotedPaper) = "{{quotedPaper}}" ) .
}