//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.31 at 12:50:46 AM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "https://github.com/ivanmihajlov/papers_please", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.ftn.papers_please.model.publishing_process;
