//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.31 at 12:50:46 AM CEST 
//


package com.ftn.papers_please.model.publishing_process;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="author-id" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="editor-id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="paper-version" maxOccurs="unbounded"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="scientific-paper-id" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="cover-letter-id" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="version-reviews" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element ref="{https://github.com/ivanmihajlov/papers_please}version-review" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}ID" /&gt;
 *       &lt;attribute name="latestVersion" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" default="1" /&gt;
 *       &lt;attribute name="status" default="NEW_SUBMISSION"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;enumeration value="NEW_SUBMISSION"/&gt;
 *             &lt;enumeration value="WAITING_FOR_REVIEWERS_ACCEPTANCE"/&gt;
 *             &lt;enumeration value="NEW_REVIEWER_NEEDED"/&gt;
 *             &lt;enumeration value="REVIEWS_ACCEPTED"/&gt;
 *             &lt;enumeration value="REVIEWS_DONE"/&gt;
 *             &lt;enumeration value="ACCEPTED"/&gt;
 *             &lt;enumeration value="REJECTED"/&gt;
 *             &lt;enumeration value="WITHDRAWN"/&gt;
 *             &lt;enumeration value="NEW_REVISION"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "authorId",
    "editorId",
    "paperVersion"
})
@XmlRootElement(name = "publishing-process")
public class PublishingProcess {

    @XmlElement(name = "author-id", required = true)
    protected String authorId;
    @XmlElement(name = "editor-id")
    protected String editorId;
    @XmlElement(name = "paper-version", required = true)
    protected List<PublishingProcess.PaperVersion> paperVersion;
    @XmlAttribute(name = "id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute(name = "latestVersion")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger latestVersion;
    @XmlAttribute(name = "status")
    protected String status;

    /**
     * Gets the value of the authorId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthorId() {
        return authorId;
    }

    /**
     * Sets the value of the authorId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthorId(String value) {
        this.authorId = value;
    }

    /**
     * Gets the value of the editorId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEditorId() {
        return editorId;
    }

    /**
     * Sets the value of the editorId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEditorId(String value) {
        this.editorId = value;
    }

    /**
     * Gets the value of the paperVersion property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the paperVersion property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPaperVersion().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PublishingProcess.PaperVersion }
     * 
     * 
     */
    public List<PublishingProcess.PaperVersion> getPaperVersion() {
        if (paperVersion == null) {
            paperVersion = new ArrayList<PublishingProcess.PaperVersion>();
        }
        return this.paperVersion;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the latestVersion property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLatestVersion() {
        if (latestVersion == null) {
            return new BigInteger("1");
        } else {
            return latestVersion;
        }
    }

    /**
     * Sets the value of the latestVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLatestVersion(BigInteger value) {
        this.latestVersion = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        if (status == null) {
            return "NEW_SUBMISSION";
        } else {
            return status;
        }
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="scientific-paper-id" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="cover-letter-id" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="version-reviews" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element ref="{https://github.com/ivanmihajlov/papers_please}version-review" maxOccurs="unbounded" minOccurs="0"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "scientificPaperId",
        "coverLetterId",
        "versionReviews"
    })
    public static class PaperVersion {

        @XmlElement(name = "scientific-paper-id", required = true)
        protected String scientificPaperId;
        @XmlElement(name = "cover-letter-id", required = true)
        protected String coverLetterId;
        @XmlElement(name = "version-reviews")
        protected PublishingProcess.PaperVersion.VersionReviews versionReviews;

        /**
         * Gets the value of the scientificPaperId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getScientificPaperId() {
            return scientificPaperId;
        }

        /**
         * Sets the value of the scientificPaperId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setScientificPaperId(String value) {
            this.scientificPaperId = value;
        }

        /**
         * Gets the value of the coverLetterId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCoverLetterId() {
            return coverLetterId;
        }

        /**
         * Sets the value of the coverLetterId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCoverLetterId(String value) {
            this.coverLetterId = value;
        }

        /**
         * Gets the value of the versionReviews property.
         * 
         * @return
         *     possible object is
         *     {@link PublishingProcess.PaperVersion.VersionReviews }
         *     
         */
        public PublishingProcess.PaperVersion.VersionReviews getVersionReviews() {
            return versionReviews;
        }

        /**
         * Sets the value of the versionReviews property.
         * 
         * @param value
         *     allowed object is
         *     {@link PublishingProcess.PaperVersion.VersionReviews }
         *     
         */
        public void setVersionReviews(PublishingProcess.PaperVersion.VersionReviews value) {
            this.versionReviews = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element ref="{https://github.com/ivanmihajlov/papers_please}version-review" maxOccurs="unbounded" minOccurs="0"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "versionReview"
        })
        public static class VersionReviews {

            @XmlElement(name = "version-review")
            protected List<VersionReview> versionReview;

            /**
             * Gets the value of the versionReview property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the versionReview property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getVersionReview().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link VersionReview }
             * 
             * 
             */
            public List<VersionReview> getVersionReview() {
                if (versionReview == null) {
                    versionReview = new ArrayList<VersionReview>();
                }
                return this.versionReview;
            }

        }

    }

}
