//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.31 at 01:51:50 AM CEST 
//


package com.ftn.papers_please.model.user;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ftn.papers_please.model.user package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _User_QNAME = new QName("https://github.com/ivanmihajlov/papers_please", "user");
    private final static QName _Role_QNAME = new QName("https://github.com/ivanmihajlov/papers_please", "role");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ftn.papers_please.model.user
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TUser }
     * 
     */
    public TUser createTUser() {
        return new TUser();
    }

    /**
     * Create an instance of {@link TRole }
     * 
     */
    public TRole createTRole() {
        return new TRole();
    }

    /**
     * Create an instance of {@link TUser.Roles }
     * 
     */
    public TUser.Roles createTUserRoles() {
        return new TUser.Roles();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TUser }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TUser }{@code >}
     */
    @XmlElementDecl(namespace = "https://github.com/ivanmihajlov/papers_please", name = "user")
    public JAXBElement<TUser> createUser(TUser value) {
        return new JAXBElement<TUser>(_User_QNAME, TUser.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TRole }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TRole }{@code >}
     */
    @XmlElementDecl(namespace = "https://github.com/ivanmihajlov/papers_please", name = "role")
    public JAXBElement<TRole> createRole(TRole value) {
        return new JAXBElement<TRole>(_Role_QNAME, TRole.class, null, value);
    }

}
