//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.31 at 12:34:18 AM CEST 
//


package com.ftn.papers_please.model.cover_letter;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="cover_letter_header" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="sender"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="sender_name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="university_name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element ref="{https://github.com/ivanmihajlov/papers_please/cover_letter}university_address"/&gt;
 *                   &lt;element name="phone_number" type="{https://github.com/ivanmihajlov/papers_please/cover_letter}TPhoneNumber"/&gt;
 *                   &lt;element name="email" type="{https://github.com/ivanmihajlov/papers_please/cover_letter}TEmail"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="recipient"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="recipient_name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="recipient_role" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="journal_name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="date" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="cover_letter_body"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;minLength value="0"/&gt;
 *               &lt;maxLength value="800"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="cover_letter_closing"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="signature" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0" form="qualified"/&gt;
 *                   &lt;element name="sender_name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="academic_title" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="department_name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="university_name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "coverLetterHeader",
    "sender",
    "recipient",
    "date",
    "coverLetterBody",
    "coverLetterClosing"
})
@XmlRootElement(name = "cover_letter")
public class CoverLetter {

    @XmlElement(name = "cover_letter_header", required = true)
    protected String coverLetterHeader;
    @XmlElement(required = true)
    protected CoverLetter.Sender sender;
    @XmlElement(required = true)
    protected CoverLetter.Recipient recipient;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar date;
    @XmlElement(name = "cover_letter_body", required = true)
    protected String coverLetterBody;
    @XmlElement(name = "cover_letter_closing", required = true)
    protected CoverLetter.CoverLetterClosing coverLetterClosing;

    /**
     * Gets the value of the coverLetterHeader property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCoverLetterHeader() {
        return coverLetterHeader;
    }

    /**
     * Sets the value of the coverLetterHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCoverLetterHeader(String value) {
        this.coverLetterHeader = value;
    }

    /**
     * Gets the value of the sender property.
     * 
     * @return
     *     possible object is
     *     {@link CoverLetter.Sender }
     *     
     */
    public CoverLetter.Sender getSender() {
        return sender;
    }

    /**
     * Sets the value of the sender property.
     * 
     * @param value
     *     allowed object is
     *     {@link CoverLetter.Sender }
     *     
     */
    public void setSender(CoverLetter.Sender value) {
        this.sender = value;
    }

    /**
     * Gets the value of the recipient property.
     * 
     * @return
     *     possible object is
     *     {@link CoverLetter.Recipient }
     *     
     */
    public CoverLetter.Recipient getRecipient() {
        return recipient;
    }

    /**
     * Sets the value of the recipient property.
     * 
     * @param value
     *     allowed object is
     *     {@link CoverLetter.Recipient }
     *     
     */
    public void setRecipient(CoverLetter.Recipient value) {
        this.recipient = value;
    }

    /**
     * Gets the value of the date property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDate(XMLGregorianCalendar value) {
        this.date = value;
    }

    /**
     * Gets the value of the coverLetterBody property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCoverLetterBody() {
        return coverLetterBody;
    }

    /**
     * Sets the value of the coverLetterBody property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCoverLetterBody(String value) {
        this.coverLetterBody = value;
    }

    /**
     * Gets the value of the coverLetterClosing property.
     * 
     * @return
     *     possible object is
     *     {@link CoverLetter.CoverLetterClosing }
     *     
     */
    public CoverLetter.CoverLetterClosing getCoverLetterClosing() {
        return coverLetterClosing;
    }

    /**
     * Sets the value of the coverLetterClosing property.
     * 
     * @param value
     *     allowed object is
     *     {@link CoverLetter.CoverLetterClosing }
     *     
     */
    public void setCoverLetterClosing(CoverLetter.CoverLetterClosing value) {
        this.coverLetterClosing = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="signature" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0" form="qualified"/&gt;
     *         &lt;element name="sender_name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="academic_title" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="department_name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="university_name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "signature",
        "senderName",
        "academicTitle",
        "departmentName",
        "universityName"
    })
    public static class CoverLetterClosing {

        protected byte[] signature;
        @XmlElement(name = "sender_name", required = true)
        protected String senderName;
        @XmlElement(name = "academic_title", required = true)
        protected String academicTitle;
        @XmlElement(name = "department_name", required = true)
        protected String departmentName;
        @XmlElement(name = "university_name", required = true)
        protected String universityName;

        /**
         * Gets the value of the signature property.
         * 
         * @return
         *     possible object is
         *     byte[]
         */
        public byte[] getSignature() {
            return signature;
        }

        /**
         * Sets the value of the signature property.
         * 
         * @param value
         *     allowed object is
         *     byte[]
         */
        public void setSignature(byte[] value) {
            this.signature = value;
        }

        /**
         * Gets the value of the senderName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSenderName() {
            return senderName;
        }

        /**
         * Sets the value of the senderName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSenderName(String value) {
            this.senderName = value;
        }

        /**
         * Gets the value of the academicTitle property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAcademicTitle() {
            return academicTitle;
        }

        /**
         * Sets the value of the academicTitle property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAcademicTitle(String value) {
            this.academicTitle = value;
        }

        /**
         * Gets the value of the departmentName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDepartmentName() {
            return departmentName;
        }

        /**
         * Sets the value of the departmentName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDepartmentName(String value) {
            this.departmentName = value;
        }

        /**
         * Gets the value of the universityName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUniversityName() {
            return universityName;
        }

        /**
         * Sets the value of the universityName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUniversityName(String value) {
            this.universityName = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="recipient_name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="recipient_role" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="journal_name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "recipientName",
        "recipientRole",
        "journalName"
    })
    public static class Recipient {

        @XmlElement(name = "recipient_name", required = true)
        protected String recipientName;
        @XmlElement(name = "recipient_role", required = true)
        protected String recipientRole;
        @XmlElement(name = "journal_name", required = true)
        protected String journalName;

        /**
         * Gets the value of the recipientName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRecipientName() {
            return recipientName;
        }

        /**
         * Sets the value of the recipientName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRecipientName(String value) {
            this.recipientName = value;
        }

        /**
         * Gets the value of the recipientRole property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRecipientRole() {
            return recipientRole;
        }

        /**
         * Sets the value of the recipientRole property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRecipientRole(String value) {
            this.recipientRole = value;
        }

        /**
         * Gets the value of the journalName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getJournalName() {
            return journalName;
        }

        /**
         * Sets the value of the journalName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setJournalName(String value) {
            this.journalName = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="sender_name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="university_name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element ref="{https://github.com/ivanmihajlov/papers_please/cover_letter}university_address"/&gt;
     *         &lt;element name="phone_number" type="{https://github.com/ivanmihajlov/papers_please/cover_letter}TPhoneNumber"/&gt;
     *         &lt;element name="email" type="{https://github.com/ivanmihajlov/papers_please/cover_letter}TEmail"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "senderName",
        "universityName",
        "universityAddress",
        "phoneNumber",
        "email"
    })
    public static class Sender {

        @XmlElement(name = "sender_name", required = true)
        protected String senderName;
        @XmlElement(name = "university_name", required = true, defaultValue = "Faculty of Technical Sciences")
        protected String universityName;
        @XmlElement(name = "university_address", required = true)
        protected UniversityAddress universityAddress;
        @XmlElement(name = "phone_number", required = true, defaultValue = "+38121/450-810")
        protected String phoneNumber;
        @XmlElement(required = true)
        protected String email;

        /**
         * Gets the value of the senderName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSenderName() {
            return senderName;
        }

        /**
         * Sets the value of the senderName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSenderName(String value) {
            this.senderName = value;
        }

        /**
         * Gets the value of the universityName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUniversityName() {
            return universityName;
        }

        /**
         * Sets the value of the universityName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUniversityName(String value) {
            this.universityName = value;
        }

        /**
         * Gets the value of the universityAddress property.
         * 
         * @return
         *     possible object is
         *     {@link UniversityAddress }
         *     
         */
        public UniversityAddress getUniversityAddress() {
            return universityAddress;
        }

        /**
         * Sets the value of the universityAddress property.
         * 
         * @param value
         *     allowed object is
         *     {@link UniversityAddress }
         *     
         */
        public void setUniversityAddress(UniversityAddress value) {
            this.universityAddress = value;
        }

        /**
         * Gets the value of the phoneNumber property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPhoneNumber() {
            return phoneNumber;
        }

        /**
         * Sets the value of the phoneNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPhoneNumber(String value) {
            this.phoneNumber = value;
        }

        /**
         * Gets the value of the email property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEmail() {
            return email;
        }

        /**
         * Sets the value of the email property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEmail(String value) {
            this.email = value;
        }

    }

}
