//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.31 at 12:34:18 AM CEST 
//


package com.ftn.papers_please.model.cover_letter;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ftn.papers_please.model.cover_letter package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ftn.papers_please.model.cover_letter
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CoverLetter }
     * 
     */
    public CoverLetter createCoverLetter() {
        return new CoverLetter();
    }

    /**
     * Create an instance of {@link CoverLetter.Sender }
     * 
     */
    public CoverLetter.Sender createCoverLetterSender() {
        return new CoverLetter.Sender();
    }

    /**
     * Create an instance of {@link CoverLetter.Recipient }
     * 
     */
    public CoverLetter.Recipient createCoverLetterRecipient() {
        return new CoverLetter.Recipient();
    }

    /**
     * Create an instance of {@link CoverLetter.CoverLetterClosing }
     * 
     */
    public CoverLetter.CoverLetterClosing createCoverLetterCoverLetterClosing() {
        return new CoverLetter.CoverLetterClosing();
    }

    /**
     * Create an instance of {@link UniversityAddress }
     * 
     */
    public UniversityAddress createUniversityAddress() {
        return new UniversityAddress();
    }

}
